// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignMessageRequest struct {
	// Message to sign.
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Public key of the private key to sign with (65 bytes uncompressed).
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignMessageRequest) Reset()         { *m = SignMessageRequest{} }
func (m *SignMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SignMessageRequest) ProtoMessage()    {}
func (*SignMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *SignMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignMessageRequest.Unmarshal(m, b)
}
func (m *SignMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignMessageRequest.Marshal(b, m, deterministic)
}
func (m *SignMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignMessageRequest.Merge(m, src)
}
func (m *SignMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SignMessageRequest.Size(m)
}
func (m *SignMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignMessageRequest proto.InternalMessageInfo

func (m *SignMessageRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SignMessageRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type SignMessageResponse struct {
	// Signature of the given message (DER-encoded).
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignMessageResponse) Reset()         { *m = SignMessageResponse{} }
func (m *SignMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SignMessageResponse) ProtoMessage()    {}
func (*SignMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *SignMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignMessageResponse.Unmarshal(m, b)
}
func (m *SignMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignMessageResponse.Marshal(b, m, deterministic)
}
func (m *SignMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignMessageResponse.Merge(m, src)
}
func (m *SignMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SignMessageResponse.Size(m)
}
func (m *SignMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignMessageResponse proto.InternalMessageInfo

func (m *SignMessageResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ListUnspentWitnessRequest struct {
	MinConfirmations     int32    `protobuf:"varint,1,opt,name=minConfirmations,proto3" json:"minConfirmations,omitempty"`
	MaxConfirmations     int32    `protobuf:"varint,2,opt,name=maxConfirmations,proto3" json:"maxConfirmations,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUnspentWitnessRequest) Reset()         { *m = ListUnspentWitnessRequest{} }
func (m *ListUnspentWitnessRequest) String() string { return proto.CompactTextString(m) }
func (*ListUnspentWitnessRequest) ProtoMessage()    {}
func (*ListUnspentWitnessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *ListUnspentWitnessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUnspentWitnessRequest.Unmarshal(m, b)
}
func (m *ListUnspentWitnessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUnspentWitnessRequest.Marshal(b, m, deterministic)
}
func (m *ListUnspentWitnessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUnspentWitnessRequest.Merge(m, src)
}
func (m *ListUnspentWitnessRequest) XXX_Size() int {
	return xxx_messageInfo_ListUnspentWitnessRequest.Size(m)
}
func (m *ListUnspentWitnessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUnspentWitnessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUnspentWitnessRequest proto.InternalMessageInfo

func (m *ListUnspentWitnessRequest) GetMinConfirmations() int32 {
	if m != nil {
		return m.MinConfirmations
	}
	return 0
}

func (m *ListUnspentWitnessRequest) GetMaxConfirmations() int32 {
	if m != nil {
		return m.MaxConfirmations
	}
	return 0
}

type ListUnspentWitnessResponse struct {
	Utxos                []*Utxo  `protobuf:"bytes,1,rep,name=utxos,proto3" json:"utxos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUnspentWitnessResponse) Reset()         { *m = ListUnspentWitnessResponse{} }
func (m *ListUnspentWitnessResponse) String() string { return proto.CompactTextString(m) }
func (*ListUnspentWitnessResponse) ProtoMessage()    {}
func (*ListUnspentWitnessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *ListUnspentWitnessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUnspentWitnessResponse.Unmarshal(m, b)
}
func (m *ListUnspentWitnessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUnspentWitnessResponse.Marshal(b, m, deterministic)
}
func (m *ListUnspentWitnessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUnspentWitnessResponse.Merge(m, src)
}
func (m *ListUnspentWitnessResponse) XXX_Size() int {
	return xxx_messageInfo_ListUnspentWitnessResponse.Size(m)
}
func (m *ListUnspentWitnessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUnspentWitnessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUnspentWitnessResponse proto.InternalMessageInfo

func (m *ListUnspentWitnessResponse) GetUtxos() []*Utxo {
	if m != nil {
		return m.Utxos
	}
	return nil
}

type Utxo struct {
	AddressType          uint32   `protobuf:"varint,1,opt,name=addressType,proto3" json:"addressType,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Confirmations        int64    `protobuf:"varint,3,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	PkScript             []byte   `protobuf:"bytes,4,opt,name=pkScript,proto3" json:"pkScript,omitempty"`
	TransactionHash      []byte   `protobuf:"bytes,5,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	Vout                 uint32   `protobuf:"varint,6,opt,name=vout,proto3" json:"vout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Utxo) Reset()         { *m = Utxo{} }
func (m *Utxo) String() string { return proto.CompactTextString(m) }
func (*Utxo) ProtoMessage()    {}
func (*Utxo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *Utxo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Utxo.Unmarshal(m, b)
}
func (m *Utxo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Utxo.Marshal(b, m, deterministic)
}
func (m *Utxo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Utxo.Merge(m, src)
}
func (m *Utxo) XXX_Size() int {
	return xxx_messageInfo_Utxo.Size(m)
}
func (m *Utxo) XXX_DiscardUnknown() {
	xxx_messageInfo_Utxo.DiscardUnknown(m)
}

var xxx_messageInfo_Utxo proto.InternalMessageInfo

func (m *Utxo) GetAddressType() uint32 {
	if m != nil {
		return m.AddressType
	}
	return 0
}

func (m *Utxo) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Utxo) GetConfirmations() int64 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *Utxo) GetPkScript() []byte {
	if m != nil {
		return m.PkScript
	}
	return nil
}

func (m *Utxo) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *Utxo) GetVout() uint32 {
	if m != nil {
		return m.Vout
	}
	return 0
}

type LockOutpointRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockOutpointRequest) Reset()         { *m = LockOutpointRequest{} }
func (m *LockOutpointRequest) String() string { return proto.CompactTextString(m) }
func (*LockOutpointRequest) ProtoMessage()    {}
func (*LockOutpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *LockOutpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockOutpointRequest.Unmarshal(m, b)
}
func (m *LockOutpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockOutpointRequest.Marshal(b, m, deterministic)
}
func (m *LockOutpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockOutpointRequest.Merge(m, src)
}
func (m *LockOutpointRequest) XXX_Size() int {
	return xxx_messageInfo_LockOutpointRequest.Size(m)
}
func (m *LockOutpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockOutpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockOutpointRequest proto.InternalMessageInfo

func (m *LockOutpointRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *LockOutpointRequest) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type LockOutpointResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockOutpointResponse) Reset()         { *m = LockOutpointResponse{} }
func (m *LockOutpointResponse) String() string { return proto.CompactTextString(m) }
func (*LockOutpointResponse) ProtoMessage()    {}
func (*LockOutpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *LockOutpointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockOutpointResponse.Unmarshal(m, b)
}
func (m *LockOutpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockOutpointResponse.Marshal(b, m, deterministic)
}
func (m *LockOutpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockOutpointResponse.Merge(m, src)
}
func (m *LockOutpointResponse) XXX_Size() int {
	return xxx_messageInfo_LockOutpointResponse.Size(m)
}
func (m *LockOutpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LockOutpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LockOutpointResponse proto.InternalMessageInfo

type UnlockOutpointRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockOutpointRequest) Reset()         { *m = UnlockOutpointRequest{} }
func (m *UnlockOutpointRequest) String() string { return proto.CompactTextString(m) }
func (*UnlockOutpointRequest) ProtoMessage()    {}
func (*UnlockOutpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *UnlockOutpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockOutpointRequest.Unmarshal(m, b)
}
func (m *UnlockOutpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockOutpointRequest.Marshal(b, m, deterministic)
}
func (m *UnlockOutpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockOutpointRequest.Merge(m, src)
}
func (m *UnlockOutpointRequest) XXX_Size() int {
	return xxx_messageInfo_UnlockOutpointRequest.Size(m)
}
func (m *UnlockOutpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockOutpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockOutpointRequest proto.InternalMessageInfo

func (m *UnlockOutpointRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *UnlockOutpointRequest) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type UnlockOutpointResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockOutpointResponse) Reset()         { *m = UnlockOutpointResponse{} }
func (m *UnlockOutpointResponse) String() string { return proto.CompactTextString(m) }
func (*UnlockOutpointResponse) ProtoMessage()    {}
func (*UnlockOutpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{8}
}

func (m *UnlockOutpointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockOutpointResponse.Unmarshal(m, b)
}
func (m *UnlockOutpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockOutpointResponse.Marshal(b, m, deterministic)
}
func (m *UnlockOutpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockOutpointResponse.Merge(m, src)
}
func (m *UnlockOutpointResponse) XXX_Size() int {
	return xxx_messageInfo_UnlockOutpointResponse.Size(m)
}
func (m *UnlockOutpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockOutpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockOutpointResponse proto.InternalMessageInfo

type NewAddressRequest struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Change               bool     `protobuf:"varint,2,opt,name=change,proto3" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAddressRequest) Reset()         { *m = NewAddressRequest{} }
func (m *NewAddressRequest) String() string { return proto.CompactTextString(m) }
func (*NewAddressRequest) ProtoMessage()    {}
func (*NewAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{9}
}

func (m *NewAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAddressRequest.Unmarshal(m, b)
}
func (m *NewAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAddressRequest.Marshal(b, m, deterministic)
}
func (m *NewAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAddressRequest.Merge(m, src)
}
func (m *NewAddressRequest) XXX_Size() int {
	return xxx_messageInfo_NewAddressRequest.Size(m)
}
func (m *NewAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewAddressRequest proto.InternalMessageInfo

func (m *NewAddressRequest) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *NewAddressRequest) GetChange() bool {
	if m != nil {
		return m.Change
	}
	return false
}

type NewAddressResponse struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAddressResponse) Reset()         { *m = NewAddressResponse{} }
func (m *NewAddressResponse) String() string { return proto.CompactTextString(m) }
func (*NewAddressResponse) ProtoMessage()    {}
func (*NewAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{10}
}

func (m *NewAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAddressResponse.Unmarshal(m, b)
}
func (m *NewAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAddressResponse.Marshal(b, m, deterministic)
}
func (m *NewAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAddressResponse.Merge(m, src)
}
func (m *NewAddressResponse) XXX_Size() int {
	return xxx_messageInfo_NewAddressResponse.Size(m)
}
func (m *NewAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewAddressResponse proto.InternalMessageInfo

func (m *NewAddressResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type FetchInputInfoRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchInputInfoRequest) Reset()         { *m = FetchInputInfoRequest{} }
func (m *FetchInputInfoRequest) String() string { return proto.CompactTextString(m) }
func (*FetchInputInfoRequest) ProtoMessage()    {}
func (*FetchInputInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{11}
}

func (m *FetchInputInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchInputInfoRequest.Unmarshal(m, b)
}
func (m *FetchInputInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchInputInfoRequest.Marshal(b, m, deterministic)
}
func (m *FetchInputInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchInputInfoRequest.Merge(m, src)
}
func (m *FetchInputInfoRequest) XXX_Size() int {
	return xxx_messageInfo_FetchInputInfoRequest.Size(m)
}
func (m *FetchInputInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchInputInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchInputInfoRequest proto.InternalMessageInfo

func (m *FetchInputInfoRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *FetchInputInfoRequest) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type FetchInputInfoResponse struct {
	Utxo                 *Utxo    `protobuf:"bytes,1,opt,name=utxo,proto3" json:"utxo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchInputInfoResponse) Reset()         { *m = FetchInputInfoResponse{} }
func (m *FetchInputInfoResponse) String() string { return proto.CompactTextString(m) }
func (*FetchInputInfoResponse) ProtoMessage()    {}
func (*FetchInputInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{12}
}

func (m *FetchInputInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchInputInfoResponse.Unmarshal(m, b)
}
func (m *FetchInputInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchInputInfoResponse.Marshal(b, m, deterministic)
}
func (m *FetchInputInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchInputInfoResponse.Merge(m, src)
}
func (m *FetchInputInfoResponse) XXX_Size() int {
	return xxx_messageInfo_FetchInputInfoResponse.Size(m)
}
func (m *FetchInputInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchInputInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchInputInfoResponse proto.InternalMessageInfo

func (m *FetchInputInfoResponse) GetUtxo() *Utxo {
	if m != nil {
		return m.Utxo
	}
	return nil
}

type SignOutputRawRequest struct {
	Transaction          *Transaction    `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	SignDescriptor       *SignDescriptor `protobuf:"bytes,2,opt,name=signDescriptor,proto3" json:"signDescriptor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SignOutputRawRequest) Reset()         { *m = SignOutputRawRequest{} }
func (m *SignOutputRawRequest) String() string { return proto.CompactTextString(m) }
func (*SignOutputRawRequest) ProtoMessage()    {}
func (*SignOutputRawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{13}
}

func (m *SignOutputRawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutputRawRequest.Unmarshal(m, b)
}
func (m *SignOutputRawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutputRawRequest.Marshal(b, m, deterministic)
}
func (m *SignOutputRawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutputRawRequest.Merge(m, src)
}
func (m *SignOutputRawRequest) XXX_Size() int {
	return xxx_messageInfo_SignOutputRawRequest.Size(m)
}
func (m *SignOutputRawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutputRawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutputRawRequest proto.InternalMessageInfo

func (m *SignOutputRawRequest) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *SignOutputRawRequest) GetSignDescriptor() *SignDescriptor {
	if m != nil {
		return m.SignDescriptor
	}
	return nil
}

type SignOutputRawResponse struct {
	// Witness signature without the hash type flag.
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutputRawResponse) Reset()         { *m = SignOutputRawResponse{} }
func (m *SignOutputRawResponse) String() string { return proto.CompactTextString(m) }
func (*SignOutputRawResponse) ProtoMessage()    {}
func (*SignOutputRawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{14}
}

func (m *SignOutputRawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutputRawResponse.Unmarshal(m, b)
}
func (m *SignOutputRawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutputRawResponse.Marshal(b, m, deterministic)
}
func (m *SignOutputRawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutputRawResponse.Merge(m, src)
}
func (m *SignOutputRawResponse) XXX_Size() int {
	return xxx_messageInfo_SignOutputRawResponse.Size(m)
}
func (m *SignOutputRawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutputRawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutputRawResponse proto.InternalMessageInfo

func (m *SignOutputRawResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ComputeInputScriptRequest struct {
	Transaction          *Transaction    `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	SignDescriptor       *SignDescriptor `protobuf:"bytes,2,opt,name=signDescriptor,proto3" json:"signDescriptor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ComputeInputScriptRequest) Reset()         { *m = ComputeInputScriptRequest{} }
func (m *ComputeInputScriptRequest) String() string { return proto.CompactTextString(m) }
func (*ComputeInputScriptRequest) ProtoMessage()    {}
func (*ComputeInputScriptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{15}
}

func (m *ComputeInputScriptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeInputScriptRequest.Unmarshal(m, b)
}
func (m *ComputeInputScriptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeInputScriptRequest.Marshal(b, m, deterministic)
}
func (m *ComputeInputScriptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeInputScriptRequest.Merge(m, src)
}
func (m *ComputeInputScriptRequest) XXX_Size() int {
	return xxx_messageInfo_ComputeInputScriptRequest.Size(m)
}
func (m *ComputeInputScriptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeInputScriptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeInputScriptRequest proto.InternalMessageInfo

func (m *ComputeInputScriptRequest) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *ComputeInputScriptRequest) GetSignDescriptor() *SignDescriptor {
	if m != nil {
		return m.SignDescriptor
	}
	return nil
}

type ComputeInputScriptResponse struct {
	Witness              [][]byte `protobuf:"bytes,1,rep,name=witness,proto3" json:"witness,omitempty"`
	SignatureScript      []byte   `protobuf:"bytes,2,opt,name=signatureScript,proto3" json:"signatureScript,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeInputScriptResponse) Reset()         { *m = ComputeInputScriptResponse{} }
func (m *ComputeInputScriptResponse) String() string { return proto.CompactTextString(m) }
func (*ComputeInputScriptResponse) ProtoMessage()    {}
func (*ComputeInputScriptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{16}
}

func (m *ComputeInputScriptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeInputScriptResponse.Unmarshal(m, b)
}
func (m *ComputeInputScriptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeInputScriptResponse.Marshal(b, m, deterministic)
}
func (m *ComputeInputScriptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeInputScriptResponse.Merge(m, src)
}
func (m *ComputeInputScriptResponse) XXX_Size() int {
	return xxx_messageInfo_ComputeInputScriptResponse.Size(m)
}
func (m *ComputeInputScriptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeInputScriptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeInputScriptResponse proto.InternalMessageInfo

func (m *ComputeInputScriptResponse) GetWitness() [][]byte {
	if m != nil {
		return m.Witness
	}
	return nil
}

func (m *ComputeInputScriptResponse) GetSignatureScript() []byte {
	if m != nil {
		return m.SignatureScript
	}
	return nil
}

type Transaction struct {
	Version              int32                `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Inputs               []*TransactionInput  `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*TransactionOutput `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	LockTime             uint32               `protobuf:"varint,4,opt,name=lockTime,proto3" json:"lockTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{17}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Transaction) GetInputs() []*TransactionInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Transaction) GetOutputs() []*TransactionOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *Transaction) GetLockTime() uint32 {
	if m != nil {
		return m.LockTime
	}
	return 0
}

type TransactionInput struct {
	TransactionHash      []byte   `protobuf:"bytes,1,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	SignatureScript      []byte   `protobuf:"bytes,3,opt,name=signatureScript,proto3" json:"signatureScript,omitempty"`
	Witness              [][]byte `protobuf:"bytes,4,rep,name=witness,proto3" json:"witness,omitempty"`
	Sequence             uint32   `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionInput) Reset()         { *m = TransactionInput{} }
func (m *TransactionInput) String() string { return proto.CompactTextString(m) }
func (*TransactionInput) ProtoMessage()    {}
func (*TransactionInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{18}
}

func (m *TransactionInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionInput.Unmarshal(m, b)
}
func (m *TransactionInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionInput.Marshal(b, m, deterministic)
}
func (m *TransactionInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionInput.Merge(m, src)
}
func (m *TransactionInput) XXX_Size() int {
	return xxx_messageInfo_TransactionInput.Size(m)
}
func (m *TransactionInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionInput.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionInput proto.InternalMessageInfo

func (m *TransactionInput) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *TransactionInput) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *TransactionInput) GetSignatureScript() []byte {
	if m != nil {
		return m.SignatureScript
	}
	return nil
}

func (m *TransactionInput) GetWitness() [][]byte {
	if m != nil {
		return m.Witness
	}
	return nil
}

func (m *TransactionInput) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type TransactionOutput struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	PkScript             []byte   `protobuf:"bytes,2,opt,name=pkScript,proto3" json:"pkScript,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionOutput) Reset()         { *m = TransactionOutput{} }
func (m *TransactionOutput) String() string { return proto.CompactTextString(m) }
func (*TransactionOutput) ProtoMessage()    {}
func (*TransactionOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{19}
}

func (m *TransactionOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionOutput.Unmarshal(m, b)
}
func (m *TransactionOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionOutput.Marshal(b, m, deterministic)
}
func (m *TransactionOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionOutput.Merge(m, src)
}
func (m *TransactionOutput) XXX_Size() int {
	return xxx_messageInfo_TransactionOutput.Size(m)
}
func (m *TransactionOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionOutput proto.InternalMessageInfo

func (m *TransactionOutput) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TransactionOutput) GetPkScript() []byte {
	if m != nil {
		return m.PkScript
	}
	return nil
}

type SignDescriptor struct {
	KeyDescriptor        *KeyDescriptor        `protobuf:"bytes,1,opt,name=keyDescriptor,proto3" json:"keyDescriptor,omitempty"`
	SingleTweak          []byte                `protobuf:"bytes,2,opt,name=singleTweak,proto3" json:"singleTweak,omitempty"`
	DoubleTweak          []byte                `protobuf:"bytes,3,opt,name=doubleTweak,proto3" json:"doubleTweak,omitempty"`
	WitnessScript        []byte                `protobuf:"bytes,4,opt,name=witnessScript,proto3" json:"witnessScript,omitempty"`
	Output               *TransactionOutput    `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	HashType             uint32                `protobuf:"varint,6,opt,name=hashType,proto3" json:"hashType,omitempty"`
	SigHashes            *TransactionSigHashes `protobuf:"bytes,7,opt,name=sigHashes,proto3" json:"sigHashes,omitempty"`
	InputIndex           uint32                `protobuf:"varint,8,opt,name=inputIndex,proto3" json:"inputIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SignDescriptor) Reset()         { *m = SignDescriptor{} }
func (m *SignDescriptor) String() string { return proto.CompactTextString(m) }
func (*SignDescriptor) ProtoMessage()    {}
func (*SignDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{20}
}

func (m *SignDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignDescriptor.Unmarshal(m, b)
}
func (m *SignDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignDescriptor.Marshal(b, m, deterministic)
}
func (m *SignDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignDescriptor.Merge(m, src)
}
func (m *SignDescriptor) XXX_Size() int {
	return xxx_messageInfo_SignDescriptor.Size(m)
}
func (m *SignDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_SignDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_SignDescriptor proto.InternalMessageInfo

func (m *SignDescriptor) GetKeyDescriptor() *KeyDescriptor {
	if m != nil {
		return m.KeyDescriptor
	}
	return nil
}

func (m *SignDescriptor) GetSingleTweak() []byte {
	if m != nil {
		return m.SingleTweak
	}
	return nil
}

func (m *SignDescriptor) GetDoubleTweak() []byte {
	if m != nil {
		return m.DoubleTweak
	}
	return nil
}

func (m *SignDescriptor) GetWitnessScript() []byte {
	if m != nil {
		return m.WitnessScript
	}
	return nil
}

func (m *SignDescriptor) GetOutput() *TransactionOutput {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *SignDescriptor) GetHashType() uint32 {
	if m != nil {
		return m.HashType
	}
	return 0
}

func (m *SignDescriptor) GetSigHashes() *TransactionSigHashes {
	if m != nil {
		return m.SigHashes
	}
	return nil
}

func (m *SignDescriptor) GetInputIndex() uint32 {
	if m != nil {
		return m.InputIndex
	}
	return 0
}

type KeyDescriptor struct {
	KeyLocator           *KeyLocator `protobuf:"bytes,1,opt,name=keyLocator,proto3" json:"keyLocator,omitempty"`
	PublicKey            []byte      `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *KeyDescriptor) Reset()         { *m = KeyDescriptor{} }
func (m *KeyDescriptor) String() string { return proto.CompactTextString(m) }
func (*KeyDescriptor) ProtoMessage()    {}
func (*KeyDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{21}
}

func (m *KeyDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyDescriptor.Unmarshal(m, b)
}
func (m *KeyDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyDescriptor.Marshal(b, m, deterministic)
}
func (m *KeyDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyDescriptor.Merge(m, src)
}
func (m *KeyDescriptor) XXX_Size() int {
	return xxx_messageInfo_KeyDescriptor.Size(m)
}
func (m *KeyDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_KeyDescriptor proto.InternalMessageInfo

func (m *KeyDescriptor) GetKeyLocator() *KeyLocator {
	if m != nil {
		return m.KeyLocator
	}
	return nil
}

func (m *KeyDescriptor) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type KeyLocator struct {
	// BIP43 path: m/1017'/coinType'/keyFamily/0/index
	KeyFamily            uint32   `protobuf:"varint,1,opt,name=keyFamily,proto3" json:"keyFamily,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyLocator) Reset()         { *m = KeyLocator{} }
func (m *KeyLocator) String() string { return proto.CompactTextString(m) }
func (*KeyLocator) ProtoMessage()    {}
func (*KeyLocator) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{22}
}

func (m *KeyLocator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyLocator.Unmarshal(m, b)
}
func (m *KeyLocator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyLocator.Marshal(b, m, deterministic)
}
func (m *KeyLocator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyLocator.Merge(m, src)
}
func (m *KeyLocator) XXX_Size() int {
	return xxx_messageInfo_KeyLocator.Size(m)
}
func (m *KeyLocator) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyLocator.DiscardUnknown(m)
}

var xxx_messageInfo_KeyLocator proto.InternalMessageInfo

func (m *KeyLocator) GetKeyFamily() uint32 {
	if m != nil {
		return m.KeyFamily
	}
	return 0
}

func (m *KeyLocator) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type TransactionSigHashes struct {
	HashPrevOuts         []byte   `protobuf:"bytes,1,opt,name=hashPrevOuts,proto3" json:"hashPrevOuts,omitempty"`
	HashSequence         []byte   `protobuf:"bytes,2,opt,name=hashSequence,proto3" json:"hashSequence,omitempty"`
	HashOutputs          []byte   `protobuf:"bytes,3,opt,name=hashOutputs,proto3" json:"hashOutputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionSigHashes) Reset()         { *m = TransactionSigHashes{} }
func (m *TransactionSigHashes) String() string { return proto.CompactTextString(m) }
func (*TransactionSigHashes) ProtoMessage()    {}
func (*TransactionSigHashes) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{23}
}

func (m *TransactionSigHashes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionSigHashes.Unmarshal(m, b)
}
func (m *TransactionSigHashes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionSigHashes.Marshal(b, m, deterministic)
}
func (m *TransactionSigHashes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionSigHashes.Merge(m, src)
}
func (m *TransactionSigHashes) XXX_Size() int {
	return xxx_messageInfo_TransactionSigHashes.Size(m)
}
func (m *TransactionSigHashes) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionSigHashes.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionSigHashes proto.InternalMessageInfo

func (m *TransactionSigHashes) GetHashPrevOuts() []byte {
	if m != nil {
		return m.HashPrevOuts
	}
	return nil
}

func (m *TransactionSigHashes) GetHashSequence() []byte {
	if m != nil {
		return m.HashSequence
	}
	return nil
}

func (m *TransactionSigHashes) GetHashOutputs() []byte {
	if m != nil {
		return m.HashOutputs
	}
	return nil
}

type GetRevocationRootKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRevocationRootKeyRequest) Reset()         { *m = GetRevocationRootKeyRequest{} }
func (m *GetRevocationRootKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GetRevocationRootKeyRequest) ProtoMessage()    {}
func (*GetRevocationRootKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{24}
}

func (m *GetRevocationRootKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRevocationRootKeyRequest.Unmarshal(m, b)
}
func (m *GetRevocationRootKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRevocationRootKeyRequest.Marshal(b, m, deterministic)
}
func (m *GetRevocationRootKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRevocationRootKeyRequest.Merge(m, src)
}
func (m *GetRevocationRootKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GetRevocationRootKeyRequest.Size(m)
}
func (m *GetRevocationRootKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRevocationRootKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRevocationRootKeyRequest proto.InternalMessageInfo

type GetRevocationRootKeyResponse struct {
	PrivateKey           []byte   `protobuf:"bytes,1,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRevocationRootKeyResponse) Reset()         { *m = GetRevocationRootKeyResponse{} }
func (m *GetRevocationRootKeyResponse) String() string { return proto.CompactTextString(m) }
func (*GetRevocationRootKeyResponse) ProtoMessage()    {}
func (*GetRevocationRootKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{25}
}

func (m *GetRevocationRootKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRevocationRootKeyResponse.Unmarshal(m, b)
}
func (m *GetRevocationRootKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRevocationRootKeyResponse.Marshal(b, m, deterministic)
}
func (m *GetRevocationRootKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRevocationRootKeyResponse.Merge(m, src)
}
func (m *GetRevocationRootKeyResponse) XXX_Size() int {
	return xxx_messageInfo_GetRevocationRootKeyResponse.Size(m)
}
func (m *GetRevocationRootKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRevocationRootKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRevocationRootKeyResponse proto.InternalMessageInfo

func (m *GetRevocationRootKeyResponse) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

type DeriveNextKeyRequest struct {
	KeyFamily            uint32   `protobuf:"varint,1,opt,name=keyFamily,proto3" json:"keyFamily,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeriveNextKeyRequest) Reset()         { *m = DeriveNextKeyRequest{} }
func (m *DeriveNextKeyRequest) String() string { return proto.CompactTextString(m) }
func (*DeriveNextKeyRequest) ProtoMessage()    {}
func (*DeriveNextKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{26}
}

func (m *DeriveNextKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeriveNextKeyRequest.Unmarshal(m, b)
}
func (m *DeriveNextKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeriveNextKeyRequest.Marshal(b, m, deterministic)
}
func (m *DeriveNextKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeriveNextKeyRequest.Merge(m, src)
}
func (m *DeriveNextKeyRequest) XXX_Size() int {
	return xxx_messageInfo_DeriveNextKeyRequest.Size(m)
}
func (m *DeriveNextKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeriveNextKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeriveNextKeyRequest proto.InternalMessageInfo

func (m *DeriveNextKeyRequest) GetKeyFamily() uint32 {
	if m != nil {
		return m.KeyFamily
	}
	return 0
}

type DeriveNextKeyResponse struct {
	KeyDescriptor        *KeyDescriptor `protobuf:"bytes,1,opt,name=keyDescriptor,proto3" json:"keyDescriptor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeriveNextKeyResponse) Reset()         { *m = DeriveNextKeyResponse{} }
func (m *DeriveNextKeyResponse) String() string { return proto.CompactTextString(m) }
func (*DeriveNextKeyResponse) ProtoMessage()    {}
func (*DeriveNextKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{27}
}

func (m *DeriveNextKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeriveNextKeyResponse.Unmarshal(m, b)
}
func (m *DeriveNextKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeriveNextKeyResponse.Marshal(b, m, deterministic)
}
func (m *DeriveNextKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeriveNextKeyResponse.Merge(m, src)
}
func (m *DeriveNextKeyResponse) XXX_Size() int {
	return xxx_messageInfo_DeriveNextKeyResponse.Size(m)
}
func (m *DeriveNextKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeriveNextKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeriveNextKeyResponse proto.InternalMessageInfo

func (m *DeriveNextKeyResponse) GetKeyDescriptor() *KeyDescriptor {
	if m != nil {
		return m.KeyDescriptor
	}
	return nil
}

type DeriveKeyRequest struct {
	KeyLocator           *KeyLocator `protobuf:"bytes,1,opt,name=keyLocator,proto3" json:"keyLocator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DeriveKeyRequest) Reset()         { *m = DeriveKeyRequest{} }
func (m *DeriveKeyRequest) String() string { return proto.CompactTextString(m) }
func (*DeriveKeyRequest) ProtoMessage()    {}
func (*DeriveKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{28}
}

func (m *DeriveKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeriveKeyRequest.Unmarshal(m, b)
}
func (m *DeriveKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeriveKeyRequest.Marshal(b, m, deterministic)
}
func (m *DeriveKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeriveKeyRequest.Merge(m, src)
}
func (m *DeriveKeyRequest) XXX_Size() int {
	return xxx_messageInfo_DeriveKeyRequest.Size(m)
}
func (m *DeriveKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeriveKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeriveKeyRequest proto.InternalMessageInfo

func (m *DeriveKeyRequest) GetKeyLocator() *KeyLocator {
	if m != nil {
		return m.KeyLocator
	}
	return nil
}

type DeriveKeyResponse struct {
	KeyDescriptor        *KeyDescriptor `protobuf:"bytes,1,opt,name=keyDescriptor,proto3" json:"keyDescriptor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeriveKeyResponse) Reset()         { *m = DeriveKeyResponse{} }
func (m *DeriveKeyResponse) String() string { return proto.CompactTextString(m) }
func (*DeriveKeyResponse) ProtoMessage()    {}
func (*DeriveKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{29}
}

func (m *DeriveKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeriveKeyResponse.Unmarshal(m, b)
}
func (m *DeriveKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeriveKeyResponse.Marshal(b, m, deterministic)
}
func (m *DeriveKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeriveKeyResponse.Merge(m, src)
}
func (m *DeriveKeyResponse) XXX_Size() int {
	return xxx_messageInfo_DeriveKeyResponse.Size(m)
}
func (m *DeriveKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeriveKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeriveKeyResponse proto.InternalMessageInfo

func (m *DeriveKeyResponse) GetKeyDescriptor() *KeyDescriptor {
	if m != nil {
		return m.KeyDescriptor
	}
	return nil
}

func init() {
	proto.RegisterType((*SignMessageRequest)(nil), "SignMessageRequest")
	proto.RegisterType((*SignMessageResponse)(nil), "SignMessageResponse")
	proto.RegisterType((*ListUnspentWitnessRequest)(nil), "ListUnspentWitnessRequest")
	proto.RegisterType((*ListUnspentWitnessResponse)(nil), "ListUnspentWitnessResponse")
	proto.RegisterType((*Utxo)(nil), "Utxo")
	proto.RegisterType((*LockOutpointRequest)(nil), "LockOutpointRequest")
	proto.RegisterType((*LockOutpointResponse)(nil), "LockOutpointResponse")
	proto.RegisterType((*UnlockOutpointRequest)(nil), "UnlockOutpointRequest")
	proto.RegisterType((*UnlockOutpointResponse)(nil), "UnlockOutpointResponse")
	proto.RegisterType((*NewAddressRequest)(nil), "NewAddressRequest")
	proto.RegisterType((*NewAddressResponse)(nil), "NewAddressResponse")
	proto.RegisterType((*FetchInputInfoRequest)(nil), "FetchInputInfoRequest")
	proto.RegisterType((*FetchInputInfoResponse)(nil), "FetchInputInfoResponse")
	proto.RegisterType((*SignOutputRawRequest)(nil), "SignOutputRawRequest")
	proto.RegisterType((*SignOutputRawResponse)(nil), "SignOutputRawResponse")
	proto.RegisterType((*ComputeInputScriptRequest)(nil), "ComputeInputScriptRequest")
	proto.RegisterType((*ComputeInputScriptResponse)(nil), "ComputeInputScriptResponse")
	proto.RegisterType((*Transaction)(nil), "Transaction")
	proto.RegisterType((*TransactionInput)(nil), "TransactionInput")
	proto.RegisterType((*TransactionOutput)(nil), "TransactionOutput")
	proto.RegisterType((*SignDescriptor)(nil), "SignDescriptor")
	proto.RegisterType((*KeyDescriptor)(nil), "KeyDescriptor")
	proto.RegisterType((*KeyLocator)(nil), "KeyLocator")
	proto.RegisterType((*TransactionSigHashes)(nil), "TransactionSigHashes")
	proto.RegisterType((*GetRevocationRootKeyRequest)(nil), "GetRevocationRootKeyRequest")
	proto.RegisterType((*GetRevocationRootKeyResponse)(nil), "GetRevocationRootKeyResponse")
	proto.RegisterType((*DeriveNextKeyRequest)(nil), "DeriveNextKeyRequest")
	proto.RegisterType((*DeriveNextKeyResponse)(nil), "DeriveNextKeyResponse")
	proto.RegisterType((*DeriveKeyRequest)(nil), "DeriveKeyRequest")
	proto.RegisterType((*DeriveKeyResponse)(nil), "DeriveKeyResponse")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 1152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdf, 0x4e, 0x1b, 0xc7,
	0x17, 0xb6, 0xc1, 0xe6, 0xcf, 0x31, 0x26, 0xe1, 0x60, 0x3b, 0x66, 0x21, 0x51, 0x34, 0xfa, 0x5d,
	0xf0, 0x4b, 0xab, 0xb9, 0x00, 0xaa, 0xa8, 0x95, 0x5a, 0x12, 0x91, 0xa6, 0x45, 0x90, 0x10, 0x0d,
	0xa0, 0x4a, 0xbd, 0xea, 0x62, 0x26, 0xb0, 0x32, 0xde, 0xdd, 0xee, 0xcc, 0x1a, 0x7c, 0xd5, 0x5e,
	0xf4, 0x31, 0xfa, 0x14, 0x7d, 0x80, 0xbe, 0x41, 0x9f, 0xa7, 0xb7, 0xd5, 0xcc, 0xec, 0x7a, 0x67,
	0xed, 0x31, 0x6d, 0x1a, 0xa9, 0x77, 0x3e, 0xdf, 0x9e, 0x3d, 0x73, 0xfe, 0xcc, 0xf9, 0xf6, 0x33,
	0x2c, 0x27, 0x71, 0x8f, 0xc6, 0x49, 0x24, 0x23, 0x72, 0x0c, 0x78, 0x1a, 0x5c, 0x85, 0x6f, 0xb8,
	0x10, 0xfe, 0x15, 0x67, 0xfc, 0xc7, 0x94, 0x0b, 0x89, 0x5d, 0x58, 0x1c, 0x18, 0xa4, 0x5b, 0x7d,
	0x5a, 0xdd, 0x5e, 0x61, 0xb9, 0x89, 0x5b, 0xb0, 0x1c, 0xa7, 0x17, 0x37, 0x41, 0xef, 0x88, 0x8f,
	0xba, 0x73, 0xfa, 0x59, 0x01, 0x90, 0x5d, 0x58, 0x2f, 0x45, 0x13, 0x71, 0x14, 0x0a, 0xfd, 0x92,
	0x08, 0xae, 0x42, 0x5f, 0xa6, 0x49, 0x1e, 0xb0, 0x00, 0x88, 0x80, 0x8d, 0xe3, 0x40, 0xc8, 0xf3,
	0x50, 0xc4, 0x3c, 0x94, 0xdf, 0x05, 0x32, 0xe4, 0x42, 0xe4, 0x99, 0x3c, 0x83, 0x87, 0x83, 0x20,
	0x3c, 0x88, 0xc2, 0xf7, 0x41, 0x32, 0xf0, 0x65, 0x10, 0x85, 0x42, 0x47, 0xa8, 0xb3, 0x29, 0x5c,
	0xfb, 0xfa, 0x77, 0x65, 0xdf, 0xb9, 0xcc, 0x77, 0x02, 0x27, 0x9f, 0x83, 0xe7, 0x3a, 0x34, 0x4b,
	0x78, 0x13, 0xea, 0xa9, 0xbc, 0x8b, 0xd4, 0x51, 0xf3, 0xdb, 0x8d, 0x9d, 0x3a, 0x3d, 0x97, 0x77,
	0x11, 0x33, 0x18, 0xf9, 0xbd, 0x0a, 0x35, 0x65, 0xe3, 0x53, 0x68, 0xf8, 0x97, 0x97, 0x09, 0x17,
	0xe2, 0x6c, 0x14, 0x9b, 0xc2, 0x9a, 0xcc, 0x86, 0xb0, 0x05, 0xf5, 0xa1, 0x7f, 0x93, 0x72, 0x9d,
	0xc6, 0x3c, 0x33, 0x06, 0xfe, 0x0f, 0x9a, 0xbd, 0x52, 0x92, 0xf3, 0xfa, 0x69, 0x19, 0x44, 0x0f,
	0x96, 0xe2, 0xfe, 0x69, 0x2f, 0x09, 0x62, 0xd9, 0xad, 0xe9, 0x9e, 0x8d, 0x6d, 0xdc, 0x86, 0x07,
	0x32, 0xf1, 0x43, 0xe1, 0xf7, 0x94, 0xef, 0xb7, 0xbe, 0xb8, 0xee, 0xd6, 0xb5, 0xcb, 0x24, 0x8c,
	0x08, 0xb5, 0x61, 0x94, 0xca, 0xee, 0x82, 0x4e, 0x4e, 0xff, 0x26, 0xfb, 0xb0, 0x7e, 0x1c, 0xf5,
	0xfa, 0x27, 0xa9, 0x8c, 0xa3, 0x20, 0x94, 0x79, 0xab, 0x11, 0x6a, 0xd7, 0x2a, 0x92, 0x19, 0x90,
	0xfe, 0xad, 0x0a, 0x08, 0xc2, 0x4b, 0x7e, 0xa7, 0x0b, 0x68, 0x32, 0x63, 0x90, 0x0e, 0xb4, 0xca,
	0x01, 0x4c, 0xdb, 0xc8, 0x4b, 0x68, 0x9f, 0x87, 0x37, 0x1f, 0x15, 0xba, 0x0b, 0x9d, 0xc9, 0x10,
	0x59, 0xf0, 0x7d, 0x58, 0x7b, 0xcb, 0x6f, 0x5f, 0x9a, 0xee, 0x5a, 0x81, 0x65, 0xd1, 0x7b, 0xfd,
	0x1b, 0x3b, 0xb0, 0xd0, 0xbb, 0xf6, 0xc3, 0x2b, 0xd3, 0xf5, 0x25, 0x96, 0x59, 0x84, 0x02, 0xda,
	0x01, 0xb2, 0x51, 0x77, 0x61, 0x31, 0x9b, 0x98, 0x0e, 0xb2, 0xcc, 0x72, 0x53, 0x55, 0xf3, 0x9a,
	0xcb, 0xde, 0xf5, 0x61, 0x18, 0xa7, 0xf2, 0x30, 0x7c, 0x1f, 0x7d, 0x78, 0x35, 0xbb, 0xd0, 0x99,
	0x0c, 0x91, 0x1d, 0xbb, 0x01, 0x35, 0x75, 0x9b, 0x74, 0x8c, 0xf1, 0x05, 0xd3, 0x10, 0xf9, 0x09,
	0x5a, 0x6a, 0x89, 0x54, 0x03, 0x52, 0xc9, 0xfc, 0xdb, 0xfc, 0x58, 0x0a, 0x0d, 0x6b, 0xba, 0xd9,
	0x9b, 0x2b, 0xf4, 0xac, 0xc0, 0x98, 0xed, 0x80, 0xcf, 0x61, 0x55, 0x2d, 0xd9, 0x2b, 0x2e, 0xf4,
	0xa5, 0x89, 0x12, 0x9d, 0x5b, 0x63, 0xe7, 0x01, 0x3d, 0x2d, 0xc1, 0x6c, 0xc2, 0x8d, 0x7c, 0x06,
	0xed, 0x89, 0x04, 0xfe, 0xd1, 0x1e, 0xff, 0x52, 0x85, 0x8d, 0x83, 0x68, 0x10, 0xa7, 0x92, 0xeb,
	0x7a, 0xcd, 0x5d, 0xfd, 0xcf, 0xb3, 0xff, 0x01, 0x3c, 0x57, 0x16, 0xc5, 0xb8, 0x6f, 0xcd, 0xb2,
	0xeb, 0xdd, 0x5e, 0x61, 0xb9, 0xa9, 0x76, 0x6a, 0x5c, 0x4b, 0xb6, 0x76, 0x86, 0xdf, 0x26, 0x61,
	0xf2, 0x6b, 0x15, 0x1a, 0x56, 0xde, 0x2a, 0xe6, 0x90, 0x27, 0x22, 0x2f, 0xab, 0xce, 0x72, 0x13,
	0xff, 0x0f, 0x0b, 0x81, 0x4a, 0x42, 0xf1, 0x90, 0x22, 0x92, 0x35, 0xbb, 0x5e, 0x9d, 0x1e, 0xcb,
	0x1c, 0xf0, 0x53, 0x58, 0x8c, 0x74, 0xc3, 0x15, 0x1d, 0x28, 0x5f, 0xb4, 0x7d, 0xb3, 0x59, 0xe4,
	0x2e, 0x8a, 0x1c, 0xd4, 0x92, 0x9c, 0x05, 0x03, 0xae, 0xc9, 0xa1, 0xc9, 0xc6, 0x36, 0xf9, 0xad,
	0x0a, 0x0f, 0x27, 0x8f, 0x71, 0x31, 0x46, 0xd5, 0xcd, 0x18, 0xce, 0x9b, 0xec, 0xea, 0xce, 0xbc,
	0xb3, 0x3b, 0x76, 0x87, 0x6b, 0xe5, 0x0e, 0x7b, 0xb0, 0x24, 0xd4, 0x6d, 0x08, 0x7b, 0x5c, 0xd3,
	0x55, 0x93, 0x8d, 0x6d, 0xf2, 0x35, 0xac, 0x4d, 0x95, 0x5b, 0xd0, 0x67, 0xd5, 0xa6, 0x4f, 0x9b,
	0x18, 0xe7, 0xca, 0xc4, 0x48, 0xfe, 0x98, 0x83, 0xd5, 0xf2, 0xfd, 0xc0, 0x3d, 0x68, 0xf6, 0xf9,
	0xc8, 0xba, 0x47, 0xe6, 0xea, 0xad, 0xd2, 0x23, 0x1b, 0x65, 0x65, 0x27, 0xc5, 0xed, 0x22, 0x08,
	0xaf, 0x6e, 0xf8, 0xd9, 0x2d, 0xf7, 0xfb, 0xd9, 0x39, 0x36, 0xa4, 0x3c, 0x2e, 0xa3, 0xf4, 0x22,
	0xf7, 0x30, 0xdd, 0xb0, 0x21, 0xc5, 0xf3, 0x59, 0xe9, 0x25, 0x1a, 0x2f, 0x83, 0xf8, 0x0c, 0x16,
	0xcc, 0x54, 0x75, 0x4f, 0xdc, 0x73, 0xcf, 0x3c, 0x54, 0xe9, 0x8a, 0x6d, 0xf4, 0xe7, 0xc6, 0x30,
	0xfa, 0xd8, 0xc6, 0x5d, 0xbd, 0x9c, 0x6a, 0x84, 0x5c, 0x74, 0x17, 0x75, 0xa8, 0xb6, 0x1d, 0xea,
	0x34, 0x7f, 0xc8, 0x0a, 0x3f, 0x7c, 0x02, 0x10, 0x18, 0x6e, 0x52, 0x13, 0x5f, 0xd2, 0x21, 0x2d,
	0x84, 0x7c, 0x0f, 0xcd, 0x52, 0x9b, 0xf0, 0x13, 0x80, 0x3e, 0x1f, 0x1d, 0x47, 0x3d, 0xbf, 0x68,
	0x65, 0x43, 0xb5, 0x32, 0x83, 0x98, 0xf5, 0xf8, 0x6f, 0xc4, 0xc2, 0x0b, 0x80, 0xa3, 0x92, 0x6f,
	0x9f, 0x8f, 0x5e, 0xfb, 0x83, 0xe0, 0x66, 0x94, 0xd1, 0x79, 0x01, 0xcc, 0xa0, 0xd7, 0x9f, 0xab,
	0xd0, 0x72, 0x55, 0x88, 0x04, 0x56, 0x54, 0x5f, 0xde, 0x25, 0x7c, 0x78, 0xa2, 0x36, 0xca, 0x5c,
	0xf5, 0x12, 0x96, 0xfb, 0x9c, 0xe6, 0x37, 0x72, 0xae, 0xf0, 0xc9, 0x31, 0x35, 0x63, 0x65, 0x9f,
	0x8c, 0x17, 0x53, 0xcf, 0xd8, 0x82, 0xc8, 0x63, 0xd8, 0xfc, 0x86, 0x4b, 0xc6, 0x87, 0xaa, 0x0c,
	0x45, 0x62, 0x51, 0x24, 0x8f, 0xf8, 0x28, 0x63, 0x3d, 0xf2, 0x15, 0x6c, 0xb9, 0x1f, 0x67, 0x74,
	0xf4, 0x04, 0x20, 0x4e, 0x82, 0xa1, 0x2f, 0xb9, 0x6a, 0x91, 0x49, 0xd3, 0x42, 0xc8, 0x1e, 0xb4,
	0x5e, 0xf1, 0x24, 0x18, 0xf2, 0xb7, 0xfc, 0xce, 0x8a, 0x7b, 0x7f, 0xb7, 0xc8, 0x1b, 0x68, 0x4f,
	0xbc, 0x95, 0x1d, 0xf7, 0xaf, 0x76, 0x81, 0xec, 0xc3, 0x43, 0x13, 0xce, 0x4a, 0xe0, 0x43, 0xee,
	0x01, 0x39, 0x84, 0x35, 0x2b, 0xc0, 0xc7, 0xe4, 0xb2, 0xf3, 0x67, 0x1d, 0x6a, 0xef, 0x82, 0x90,
	0xe3, 0x17, 0xd0, 0xb0, 0xa4, 0x26, 0xae, 0xd3, 0x69, 0x19, 0xeb, 0xb5, 0xa8, 0x43, 0x8d, 0x92,
	0x0a, 0x9e, 0x00, 0x4e, 0x8b, 0x3f, 0xf4, 0xe8, 0x4c, 0x19, 0xea, 0x6d, 0xd2, 0xd9, 0x6a, 0x91,
	0x54, 0xf0, 0x4b, 0x58, 0xb1, 0x05, 0x11, 0xb6, 0xa8, 0x43, 0x60, 0x79, 0x6d, 0xea, 0x54, 0x4d,
	0x15, 0x3c, 0x80, 0xd5, 0xb2, 0xe8, 0xc1, 0x0e, 0x75, 0x0a, 0x29, 0xef, 0x11, 0x9d, 0xa1, 0x8e,
	0x2a, 0xf8, 0x1c, 0xa0, 0x90, 0x37, 0x88, 0x74, 0x4a, 0x2c, 0x79, 0xeb, 0x74, 0x5a, 0xff, 0x98,
	0xd3, 0xcb, 0x22, 0x05, 0x3b, 0xd4, 0x29, 0x7c, 0xbc, 0x47, 0xd4, 0xad, 0x66, 0x48, 0x05, 0x5f,
	0x40, 0xb3, 0xa4, 0x19, 0xb0, 0x4d, 0x5d, 0x22, 0xc6, 0xeb, 0x50, 0xa7, 0xb4, 0x30, 0x43, 0x99,
	0xfe, 0x6e, 0xa3, 0x47, 0x67, 0x4a, 0x0a, 0x6f, 0x93, 0xce, 0xfe, 0xd0, 0x93, 0x0a, 0x9e, 0x43,
	0xcb, 0xb5, 0x7b, 0xb8, 0x45, 0xef, 0xd9, 0x58, 0xef, 0x31, 0xbd, 0x6f, 0x61, 0x4d, 0xa5, 0xa5,
	0xe5, 0xc2, 0x36, 0x75, 0xad, 0xa8, 0xd7, 0xa1, 0xce, 0x1d, 0x24, 0x15, 0xdc, 0x83, 0xe5, 0xf1,
	0x3a, 0xe0, 0x1a, 0x9d, 0xdc, 0x2d, 0x0f, 0xe9, 0xd4, 0xb6, 0x90, 0xca, 0xc5, 0x82, 0xfe, 0xc3,
	0xb6, 0xfb, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x2a, 0x0f, 0xcf, 0xbd, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PineClient is the client API for Pine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PineClient interface {
	// SignMessage signs a message using the user's private key.
	SignMessage(ctx context.Context, in *SignMessageRequest, opts ...grpc.CallOption) (*SignMessageResponse, error)
	// ListUnspentWitness returns a list of unspent transaction outputs from
	// the user's wallet.
	ListUnspentWitness(ctx context.Context, in *ListUnspentWitnessRequest, opts ...grpc.CallOption) (*ListUnspentWitnessResponse, error)
	// LockOutpoint marks an unspent transaction output as reserved excluding
	// it from coin selection.
	LockOutpoint(ctx context.Context, in *LockOutpointRequest, opts ...grpc.CallOption) (*LockOutpointResponse, error)
	// UnlockOutpoint unmarks an unspent transaction output as reserved making
	// it eligible for coin selection.
	UnlockOutpoint(ctx context.Context, in *UnlockOutpointRequest, opts ...grpc.CallOption) (*UnlockOutpointResponse, error)
	// NewAddress returns the next external or internal address for the wallet.
	NewAddress(ctx context.Context, in *NewAddressRequest, opts ...grpc.CallOption) (*NewAddressResponse, error)
	// FetchInputInfo returns information about a transaction output.
	FetchInputInfo(ctx context.Context, in *FetchInputInfoRequest, opts ...grpc.CallOption) (*FetchInputInfoResponse, error)
	// SignOutputRaw signs a transaction.
	SignOutputRaw(ctx context.Context, in *SignOutputRawRequest, opts ...grpc.CallOption) (*SignOutputRawResponse, error)
	// ComputeInputScript computes an input script for a transaction.
	ComputeInputScript(ctx context.Context, in *ComputeInputScriptRequest, opts ...grpc.CallOption) (*ComputeInputScriptResponse, error)
	// GetRevocationRootKey returns a private key to be used as a revocation root.
	// TODO: Create an API for getting revocation secrets instead of exposing private keys.
	GetRevocationRootKey(ctx context.Context, in *GetRevocationRootKeyRequest, opts ...grpc.CallOption) (*GetRevocationRootKeyResponse, error)
	// DeriveNextKey returns a key descriptor for the next key for the specified key family.
	DeriveNextKey(ctx context.Context, in *DeriveNextKeyRequest, opts ...grpc.CallOption) (*DeriveNextKeyResponse, error)
	// DeriveKey returns a key descriptor for a private key specified by
	// the passed key locator.
	DeriveKey(ctx context.Context, in *DeriveKeyRequest, opts ...grpc.CallOption) (*DeriveKeyResponse, error)
}

type pineClient struct {
	cc *grpc.ClientConn
}

func NewPineClient(cc *grpc.ClientConn) PineClient {
	return &pineClient{cc}
}

func (c *pineClient) SignMessage(ctx context.Context, in *SignMessageRequest, opts ...grpc.CallOption) (*SignMessageResponse, error) {
	out := new(SignMessageResponse)
	err := c.cc.Invoke(ctx, "/Pine/SignMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pineClient) ListUnspentWitness(ctx context.Context, in *ListUnspentWitnessRequest, opts ...grpc.CallOption) (*ListUnspentWitnessResponse, error) {
	out := new(ListUnspentWitnessResponse)
	err := c.cc.Invoke(ctx, "/Pine/ListUnspentWitness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pineClient) LockOutpoint(ctx context.Context, in *LockOutpointRequest, opts ...grpc.CallOption) (*LockOutpointResponse, error) {
	out := new(LockOutpointResponse)
	err := c.cc.Invoke(ctx, "/Pine/LockOutpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pineClient) UnlockOutpoint(ctx context.Context, in *UnlockOutpointRequest, opts ...grpc.CallOption) (*UnlockOutpointResponse, error) {
	out := new(UnlockOutpointResponse)
	err := c.cc.Invoke(ctx, "/Pine/UnlockOutpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pineClient) NewAddress(ctx context.Context, in *NewAddressRequest, opts ...grpc.CallOption) (*NewAddressResponse, error) {
	out := new(NewAddressResponse)
	err := c.cc.Invoke(ctx, "/Pine/NewAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pineClient) FetchInputInfo(ctx context.Context, in *FetchInputInfoRequest, opts ...grpc.CallOption) (*FetchInputInfoResponse, error) {
	out := new(FetchInputInfoResponse)
	err := c.cc.Invoke(ctx, "/Pine/FetchInputInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pineClient) SignOutputRaw(ctx context.Context, in *SignOutputRawRequest, opts ...grpc.CallOption) (*SignOutputRawResponse, error) {
	out := new(SignOutputRawResponse)
	err := c.cc.Invoke(ctx, "/Pine/SignOutputRaw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pineClient) ComputeInputScript(ctx context.Context, in *ComputeInputScriptRequest, opts ...grpc.CallOption) (*ComputeInputScriptResponse, error) {
	out := new(ComputeInputScriptResponse)
	err := c.cc.Invoke(ctx, "/Pine/ComputeInputScript", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pineClient) GetRevocationRootKey(ctx context.Context, in *GetRevocationRootKeyRequest, opts ...grpc.CallOption) (*GetRevocationRootKeyResponse, error) {
	out := new(GetRevocationRootKeyResponse)
	err := c.cc.Invoke(ctx, "/Pine/GetRevocationRootKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pineClient) DeriveNextKey(ctx context.Context, in *DeriveNextKeyRequest, opts ...grpc.CallOption) (*DeriveNextKeyResponse, error) {
	out := new(DeriveNextKeyResponse)
	err := c.cc.Invoke(ctx, "/Pine/DeriveNextKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pineClient) DeriveKey(ctx context.Context, in *DeriveKeyRequest, opts ...grpc.CallOption) (*DeriveKeyResponse, error) {
	out := new(DeriveKeyResponse)
	err := c.cc.Invoke(ctx, "/Pine/DeriveKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PineServer is the server API for Pine service.
type PineServer interface {
	// SignMessage signs a message using the user's private key.
	SignMessage(context.Context, *SignMessageRequest) (*SignMessageResponse, error)
	// ListUnspentWitness returns a list of unspent transaction outputs from
	// the user's wallet.
	ListUnspentWitness(context.Context, *ListUnspentWitnessRequest) (*ListUnspentWitnessResponse, error)
	// LockOutpoint marks an unspent transaction output as reserved excluding
	// it from coin selection.
	LockOutpoint(context.Context, *LockOutpointRequest) (*LockOutpointResponse, error)
	// UnlockOutpoint unmarks an unspent transaction output as reserved making
	// it eligible for coin selection.
	UnlockOutpoint(context.Context, *UnlockOutpointRequest) (*UnlockOutpointResponse, error)
	// NewAddress returns the next external or internal address for the wallet.
	NewAddress(context.Context, *NewAddressRequest) (*NewAddressResponse, error)
	// FetchInputInfo returns information about a transaction output.
	FetchInputInfo(context.Context, *FetchInputInfoRequest) (*FetchInputInfoResponse, error)
	// SignOutputRaw signs a transaction.
	SignOutputRaw(context.Context, *SignOutputRawRequest) (*SignOutputRawResponse, error)
	// ComputeInputScript computes an input script for a transaction.
	ComputeInputScript(context.Context, *ComputeInputScriptRequest) (*ComputeInputScriptResponse, error)
	// GetRevocationRootKey returns a private key to be used as a revocation root.
	// TODO: Create an API for getting revocation secrets instead of exposing private keys.
	GetRevocationRootKey(context.Context, *GetRevocationRootKeyRequest) (*GetRevocationRootKeyResponse, error)
	// DeriveNextKey returns a key descriptor for the next key for the specified key family.
	DeriveNextKey(context.Context, *DeriveNextKeyRequest) (*DeriveNextKeyResponse, error)
	// DeriveKey returns a key descriptor for a private key specified by
	// the passed key locator.
	DeriveKey(context.Context, *DeriveKeyRequest) (*DeriveKeyResponse, error)
}

// UnimplementedPineServer can be embedded to have forward compatible implementations.
type UnimplementedPineServer struct {
}

func (*UnimplementedPineServer) SignMessage(ctx context.Context, req *SignMessageRequest) (*SignMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignMessage not implemented")
}
func (*UnimplementedPineServer) ListUnspentWitness(ctx context.Context, req *ListUnspentWitnessRequest) (*ListUnspentWitnessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUnspentWitness not implemented")
}
func (*UnimplementedPineServer) LockOutpoint(ctx context.Context, req *LockOutpointRequest) (*LockOutpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockOutpoint not implemented")
}
func (*UnimplementedPineServer) UnlockOutpoint(ctx context.Context, req *UnlockOutpointRequest) (*UnlockOutpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockOutpoint not implemented")
}
func (*UnimplementedPineServer) NewAddress(ctx context.Context, req *NewAddressRequest) (*NewAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewAddress not implemented")
}
func (*UnimplementedPineServer) FetchInputInfo(ctx context.Context, req *FetchInputInfoRequest) (*FetchInputInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchInputInfo not implemented")
}
func (*UnimplementedPineServer) SignOutputRaw(ctx context.Context, req *SignOutputRawRequest) (*SignOutputRawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignOutputRaw not implemented")
}
func (*UnimplementedPineServer) ComputeInputScript(ctx context.Context, req *ComputeInputScriptRequest) (*ComputeInputScriptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputeInputScript not implemented")
}
func (*UnimplementedPineServer) GetRevocationRootKey(ctx context.Context, req *GetRevocationRootKeyRequest) (*GetRevocationRootKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRevocationRootKey not implemented")
}
func (*UnimplementedPineServer) DeriveNextKey(ctx context.Context, req *DeriveNextKeyRequest) (*DeriveNextKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeriveNextKey not implemented")
}
func (*UnimplementedPineServer) DeriveKey(ctx context.Context, req *DeriveKeyRequest) (*DeriveKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeriveKey not implemented")
}

func RegisterPineServer(s *grpc.Server, srv PineServer) {
	s.RegisterService(&_Pine_serviceDesc, srv)
}

func _Pine_SignMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PineServer).SignMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pine/SignMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PineServer).SignMessage(ctx, req.(*SignMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pine_ListUnspentWitness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUnspentWitnessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PineServer).ListUnspentWitness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pine/ListUnspentWitness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PineServer).ListUnspentWitness(ctx, req.(*ListUnspentWitnessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pine_LockOutpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockOutpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PineServer).LockOutpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pine/LockOutpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PineServer).LockOutpoint(ctx, req.(*LockOutpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pine_UnlockOutpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockOutpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PineServer).UnlockOutpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pine/UnlockOutpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PineServer).UnlockOutpoint(ctx, req.(*UnlockOutpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pine_NewAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PineServer).NewAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pine/NewAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PineServer).NewAddress(ctx, req.(*NewAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pine_FetchInputInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchInputInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PineServer).FetchInputInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pine/FetchInputInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PineServer).FetchInputInfo(ctx, req.(*FetchInputInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pine_SignOutputRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignOutputRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PineServer).SignOutputRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pine/SignOutputRaw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PineServer).SignOutputRaw(ctx, req.(*SignOutputRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pine_ComputeInputScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeInputScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PineServer).ComputeInputScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pine/ComputeInputScript",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PineServer).ComputeInputScript(ctx, req.(*ComputeInputScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pine_GetRevocationRootKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRevocationRootKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PineServer).GetRevocationRootKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pine/GetRevocationRootKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PineServer).GetRevocationRootKey(ctx, req.(*GetRevocationRootKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pine_DeriveNextKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeriveNextKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PineServer).DeriveNextKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pine/DeriveNextKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PineServer).DeriveNextKey(ctx, req.(*DeriveNextKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pine_DeriveKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeriveKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PineServer).DeriveKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pine/DeriveKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PineServer).DeriveKey(ctx, req.(*DeriveKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Pine",
	HandlerType: (*PineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignMessage",
			Handler:    _Pine_SignMessage_Handler,
		},
		{
			MethodName: "ListUnspentWitness",
			Handler:    _Pine_ListUnspentWitness_Handler,
		},
		{
			MethodName: "LockOutpoint",
			Handler:    _Pine_LockOutpoint_Handler,
		},
		{
			MethodName: "UnlockOutpoint",
			Handler:    _Pine_UnlockOutpoint_Handler,
		},
		{
			MethodName: "NewAddress",
			Handler:    _Pine_NewAddress_Handler,
		},
		{
			MethodName: "FetchInputInfo",
			Handler:    _Pine_FetchInputInfo_Handler,
		},
		{
			MethodName: "SignOutputRaw",
			Handler:    _Pine_SignOutputRaw_Handler,
		},
		{
			MethodName: "ComputeInputScript",
			Handler:    _Pine_ComputeInputScript_Handler,
		},
		{
			MethodName: "GetRevocationRootKey",
			Handler:    _Pine_GetRevocationRootKey_Handler,
		},
		{
			MethodName: "DeriveNextKey",
			Handler:    _Pine_DeriveNextKey_Handler,
		},
		{
			MethodName: "DeriveKey",
			Handler:    _Pine_DeriveKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
