// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pine.proto

package pine

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignMessageRequest struct {
	// Message to sign.
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Public key of the private key to sign with (65 bytes uncompressed).
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignMessageRequest) Reset()         { *m = SignMessageRequest{} }
func (m *SignMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SignMessageRequest) ProtoMessage()    {}
func (*SignMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d4b5db5d7eac1f0, []int{0}
}

func (m *SignMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignMessageRequest.Unmarshal(m, b)
}
func (m *SignMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignMessageRequest.Marshal(b, m, deterministic)
}
func (m *SignMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignMessageRequest.Merge(m, src)
}
func (m *SignMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SignMessageRequest.Size(m)
}
func (m *SignMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignMessageRequest proto.InternalMessageInfo

func (m *SignMessageRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SignMessageRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type SignMessageResponse struct {
	// Signature of the given message (DER-encoded).
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignMessageResponse) Reset()         { *m = SignMessageResponse{} }
func (m *SignMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SignMessageResponse) ProtoMessage()    {}
func (*SignMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d4b5db5d7eac1f0, []int{1}
}

func (m *SignMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignMessageResponse.Unmarshal(m, b)
}
func (m *SignMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignMessageResponse.Marshal(b, m, deterministic)
}
func (m *SignMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignMessageResponse.Merge(m, src)
}
func (m *SignMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SignMessageResponse.Size(m)
}
func (m *SignMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignMessageResponse proto.InternalMessageInfo

func (m *SignMessageResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ListUnspentWitnessRequest struct {
	MinConfirmations     int32    `protobuf:"varint,1,opt,name=minConfirmations,proto3" json:"minConfirmations,omitempty"`
	MaxConfirmations     int32    `protobuf:"varint,2,opt,name=maxConfirmations,proto3" json:"maxConfirmations,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUnspentWitnessRequest) Reset()         { *m = ListUnspentWitnessRequest{} }
func (m *ListUnspentWitnessRequest) String() string { return proto.CompactTextString(m) }
func (*ListUnspentWitnessRequest) ProtoMessage()    {}
func (*ListUnspentWitnessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d4b5db5d7eac1f0, []int{2}
}

func (m *ListUnspentWitnessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUnspentWitnessRequest.Unmarshal(m, b)
}
func (m *ListUnspentWitnessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUnspentWitnessRequest.Marshal(b, m, deterministic)
}
func (m *ListUnspentWitnessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUnspentWitnessRequest.Merge(m, src)
}
func (m *ListUnspentWitnessRequest) XXX_Size() int {
	return xxx_messageInfo_ListUnspentWitnessRequest.Size(m)
}
func (m *ListUnspentWitnessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUnspentWitnessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUnspentWitnessRequest proto.InternalMessageInfo

func (m *ListUnspentWitnessRequest) GetMinConfirmations() int32 {
	if m != nil {
		return m.MinConfirmations
	}
	return 0
}

func (m *ListUnspentWitnessRequest) GetMaxConfirmations() int32 {
	if m != nil {
		return m.MaxConfirmations
	}
	return 0
}

type ListUnspentWitnessResponse struct {
	Utxos                []*Utxo  `protobuf:"bytes,1,rep,name=utxos,proto3" json:"utxos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUnspentWitnessResponse) Reset()         { *m = ListUnspentWitnessResponse{} }
func (m *ListUnspentWitnessResponse) String() string { return proto.CompactTextString(m) }
func (*ListUnspentWitnessResponse) ProtoMessage()    {}
func (*ListUnspentWitnessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d4b5db5d7eac1f0, []int{3}
}

func (m *ListUnspentWitnessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUnspentWitnessResponse.Unmarshal(m, b)
}
func (m *ListUnspentWitnessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUnspentWitnessResponse.Marshal(b, m, deterministic)
}
func (m *ListUnspentWitnessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUnspentWitnessResponse.Merge(m, src)
}
func (m *ListUnspentWitnessResponse) XXX_Size() int {
	return xxx_messageInfo_ListUnspentWitnessResponse.Size(m)
}
func (m *ListUnspentWitnessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUnspentWitnessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUnspentWitnessResponse proto.InternalMessageInfo

func (m *ListUnspentWitnessResponse) GetUtxos() []*Utxo {
	if m != nil {
		return m.Utxos
	}
	return nil
}

type Utxo struct {
	AddressType          uint32    `protobuf:"varint,1,opt,name=addressType,proto3" json:"addressType,omitempty"`
	Value                int64     `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Confirmations        int64     `protobuf:"varint,3,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	PkScript             []byte    `protobuf:"bytes,4,opt,name=pkScript,proto3" json:"pkScript,omitempty"`
	RedeemScript         []byte    `protobuf:"bytes,5,opt,name=redeemScript,proto3" json:"redeemScript,omitempty"`
	WitnessScript        []byte    `protobuf:"bytes,6,opt,name=witnessScript,proto3" json:"witnessScript,omitempty"`
	OutPoint             *OutPoint `protobuf:"bytes,7,opt,name=outPoint,proto3" json:"outPoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Utxo) Reset()         { *m = Utxo{} }
func (m *Utxo) String() string { return proto.CompactTextString(m) }
func (*Utxo) ProtoMessage()    {}
func (*Utxo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d4b5db5d7eac1f0, []int{4}
}

func (m *Utxo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Utxo.Unmarshal(m, b)
}
func (m *Utxo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Utxo.Marshal(b, m, deterministic)
}
func (m *Utxo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Utxo.Merge(m, src)
}
func (m *Utxo) XXX_Size() int {
	return xxx_messageInfo_Utxo.Size(m)
}
func (m *Utxo) XXX_DiscardUnknown() {
	xxx_messageInfo_Utxo.DiscardUnknown(m)
}

var xxx_messageInfo_Utxo proto.InternalMessageInfo

func (m *Utxo) GetAddressType() uint32 {
	if m != nil {
		return m.AddressType
	}
	return 0
}

func (m *Utxo) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Utxo) GetConfirmations() int64 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *Utxo) GetPkScript() []byte {
	if m != nil {
		return m.PkScript
	}
	return nil
}

func (m *Utxo) GetRedeemScript() []byte {
	if m != nil {
		return m.RedeemScript
	}
	return nil
}

func (m *Utxo) GetWitnessScript() []byte {
	if m != nil {
		return m.WitnessScript
	}
	return nil
}

func (m *Utxo) GetOutPoint() *OutPoint {
	if m != nil {
		return m.OutPoint
	}
	return nil
}

// OutPoint represents a transaction output.
type OutPoint struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutPoint) Reset()         { *m = OutPoint{} }
func (m *OutPoint) String() string { return proto.CompactTextString(m) }
func (*OutPoint) ProtoMessage()    {}
func (*OutPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d4b5db5d7eac1f0, []int{5}
}

func (m *OutPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutPoint.Unmarshal(m, b)
}
func (m *OutPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutPoint.Marshal(b, m, deterministic)
}
func (m *OutPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutPoint.Merge(m, src)
}
func (m *OutPoint) XXX_Size() int {
	return xxx_messageInfo_OutPoint.Size(m)
}
func (m *OutPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_OutPoint.DiscardUnknown(m)
}

var xxx_messageInfo_OutPoint proto.InternalMessageInfo

func (m *OutPoint) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *OutPoint) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*SignMessageRequest)(nil), "SignMessageRequest")
	proto.RegisterType((*SignMessageResponse)(nil), "SignMessageResponse")
	proto.RegisterType((*ListUnspentWitnessRequest)(nil), "ListUnspentWitnessRequest")
	proto.RegisterType((*ListUnspentWitnessResponse)(nil), "ListUnspentWitnessResponse")
	proto.RegisterType((*Utxo)(nil), "Utxo")
	proto.RegisterType((*OutPoint)(nil), "OutPoint")
}

func init() { proto.RegisterFile("pine.proto", fileDescriptor_2d4b5db5d7eac1f0) }

var fileDescriptor_2d4b5db5d7eac1f0 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x8e, 0xda, 0x30,
	0x10, 0xc6, 0x37, 0x4b, 0xb2, 0xcb, 0x4e, 0x16, 0xa9, 0x1a, 0x38, 0xa4, 0xa1, 0x07, 0x64, 0xb5,
	0x12, 0xea, 0x21, 0x07, 0xe8, 0xa5, 0xbd, 0xf6, 0x58, 0x2a, 0x90, 0x29, 0xea, 0x39, 0x10, 0x17,
	0xac, 0x12, 0xdb, 0x8d, 0x9d, 0x36, 0x3c, 0x47, 0x9f, 0xb4, 0x6f, 0x50, 0xc5, 0x49, 0x80, 0x2c,
	0x70, 0xcb, 0xfc, 0xe6, 0xcb, 0xfc, 0xf1, 0x7c, 0x00, 0x8a, 0x0b, 0x16, 0xa9, 0x4c, 0x1a, 0x49,
	0x66, 0x80, 0x4b, 0xbe, 0x15, 0x5f, 0x99, 0xd6, 0xf1, 0x96, 0x51, 0xf6, 0x2b, 0x67, 0xda, 0x60,
	0x00, 0x8f, 0x69, 0x45, 0x02, 0x67, 0xe4, 0x8c, 0x9f, 0x69, 0x13, 0xe2, 0x1b, 0x78, 0x52, 0xf9,
	0x7a, 0xcf, 0x37, 0x5f, 0xd8, 0x21, 0xb8, 0xb7, 0xb9, 0x13, 0x20, 0x53, 0xe8, 0xb7, 0xaa, 0x69,
	0x25, 0x85, 0xb6, 0x3f, 0x69, 0xbe, 0x15, 0xb1, 0xc9, 0xb3, 0xa6, 0xe0, 0x09, 0x10, 0x0d, 0xaf,
	0x67, 0x5c, 0x9b, 0x95, 0xd0, 0x8a, 0x09, 0xf3, 0x9d, 0x1b, 0xc1, 0xb4, 0x6e, 0x26, 0x79, 0x0f,
	0xaf, 0x52, 0x2e, 0x3e, 0x4b, 0xf1, 0x83, 0x67, 0x69, 0x6c, 0xb8, 0x14, 0xda, 0x56, 0xf0, 0xe8,
	0x05, 0xb7, 0xda, 0xb8, 0x68, 0x6b, 0xef, 0x6b, 0xed, 0x0b, 0x4e, 0x3e, 0x42, 0x78, 0xad, 0x69,
	0x3d, 0xf0, 0x10, 0xbc, 0xdc, 0x14, 0xb2, 0x6c, 0xd5, 0x19, 0xfb, 0x13, 0x2f, 0x5a, 0x99, 0x42,
	0xd2, 0x8a, 0x91, 0x7f, 0x0e, 0xb8, 0x65, 0x8c, 0x23, 0xf0, 0xe3, 0x24, 0xc9, 0x98, 0xd6, 0xdf,
	0x0e, 0xaa, 0x5a, 0xac, 0x47, 0xcf, 0x11, 0x0e, 0xc0, 0xfb, 0x1d, 0xef, 0x73, 0x66, 0xc7, 0xe8,
	0xd0, 0x2a, 0xc0, 0xb7, 0xd0, 0xdb, 0xb4, 0x86, 0xec, 0xd8, 0x6c, 0x1b, 0x62, 0x08, 0x5d, 0xf5,
	0x73, 0xb9, 0xc9, 0xb8, 0x32, 0x81, 0x6b, 0xdf, 0xec, 0x18, 0x23, 0x81, 0xe7, 0x8c, 0x25, 0x8c,
	0xa5, 0x75, 0xde, 0xb3, 0xf9, 0x16, 0x2b, 0xbb, 0xfc, 0xa9, 0xd6, 0xaa, 0x45, 0x0f, 0x56, 0xd4,
	0x86, 0xf8, 0x0e, 0xba, 0x32, 0x37, 0x0b, 0xc9, 0x85, 0x09, 0x1e, 0x47, 0xce, 0xd8, 0x9f, 0x3c,
	0x45, 0xf3, 0x1a, 0xd0, 0x63, 0x8a, 0x7c, 0x80, 0x6e, 0x43, 0x11, 0xc1, 0xdd, 0xc5, 0x7a, 0x57,
	0x1f, 0xd2, 0x7e, 0x97, 0x8b, 0x72, 0x91, 0xb0, 0xc2, 0x2e, 0xda, 0xa3, 0x55, 0x30, 0xf9, 0xeb,
	0x80, 0xbb, 0xe0, 0x82, 0xe1, 0x27, 0xf0, 0xcf, 0x7c, 0x81, 0xfd, 0xe8, 0xd2, 0x73, 0xe1, 0x20,
	0xba, 0x62, 0x1d, 0x72, 0x87, 0x73, 0xc0, 0xcb, 0x4b, 0x61, 0x18, 0xdd, 0xf4, 0x4c, 0x38, 0x8c,
	0x6e, 0x9f, 0x96, 0xdc, 0xad, 0x1f, 0xac, 0xf3, 0xa7, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe6,
	0x0e, 0xb6, 0x5f, 0x07, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PineClient is the client API for Pine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PineClient interface {
	SignMessage(ctx context.Context, in *SignMessageRequest, opts ...grpc.CallOption) (*SignMessageResponse, error)
	ListUnspentWitness(ctx context.Context, in *ListUnspentWitnessRequest, opts ...grpc.CallOption) (*ListUnspentWitnessResponse, error)
}

type pineClient struct {
	cc *grpc.ClientConn
}

func NewPineClient(cc *grpc.ClientConn) PineClient {
	return &pineClient{cc}
}

func (c *pineClient) SignMessage(ctx context.Context, in *SignMessageRequest, opts ...grpc.CallOption) (*SignMessageResponse, error) {
	out := new(SignMessageResponse)
	err := c.cc.Invoke(ctx, "/Pine/SignMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pineClient) ListUnspentWitness(ctx context.Context, in *ListUnspentWitnessRequest, opts ...grpc.CallOption) (*ListUnspentWitnessResponse, error) {
	out := new(ListUnspentWitnessResponse)
	err := c.cc.Invoke(ctx, "/Pine/ListUnspentWitness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PineServer is the server API for Pine service.
type PineServer interface {
	SignMessage(context.Context, *SignMessageRequest) (*SignMessageResponse, error)
	ListUnspentWitness(context.Context, *ListUnspentWitnessRequest) (*ListUnspentWitnessResponse, error)
}

// UnimplementedPineServer can be embedded to have forward compatible implementations.
type UnimplementedPineServer struct {
}

func (*UnimplementedPineServer) SignMessage(ctx context.Context, req *SignMessageRequest) (*SignMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignMessage not implemented")
}
func (*UnimplementedPineServer) ListUnspentWitness(ctx context.Context, req *ListUnspentWitnessRequest) (*ListUnspentWitnessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUnspentWitness not implemented")
}

func RegisterPineServer(s *grpc.Server, srv PineServer) {
	s.RegisterService(&_Pine_serviceDesc, srv)
}

func _Pine_SignMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PineServer).SignMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pine/SignMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PineServer).SignMessage(ctx, req.(*SignMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pine_ListUnspentWitness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUnspentWitnessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PineServer).ListUnspentWitness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pine/ListUnspentWitness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PineServer).ListUnspentWitness(ctx, req.(*ListUnspentWitnessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Pine",
	HandlerType: (*PineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignMessage",
			Handler:    _Pine_SignMessage_Handler,
		},
		{
			MethodName: "ListUnspentWitness",
			Handler:    _Pine_ListUnspentWitness_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pine.proto",
}
